### ISSUE TITLE
help

### ISSUE THREAD

**Issue by cypherpunks132** [CommitteeOfZero/impacto#6]
every time i try to play chaos head love chu chu ps3 with impacto i get this(error message?)
![chlcchelp](https://user-images.githubusercontent.com/67905137/124379651-9c576b00-dcb8-11eb-933c-0dd0db88719f.PNG)

**Comment by MrRevo3D** [comment]
@cypherpunks132 you have to provide a SYSTEM.DAT save file since impacto doesn't yet create one itself. You can use rpcs3 to run the game there once and generate that file, then place it in `games/chlcc/savedata`. Alternatively you can disable the save system and it should work I think? (In `profiles/chlcc/savedata.js` change `SaveDataType.CHLCC` to `SaveDataType.None`) Save menu is not implemented yet anyway.

**Comment by cypherpunks132** [comment]
ok
